
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test_unitaire_app
    restart: unless-stopped

  tests:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: test_unitaire_tests
    volumes:
      - .:/app
    working_dir: /app
    command: ["dotnet", "test", "Test_Unitaire_1_TestClasse/Test_Unitaire_1_TestClasse.csproj"]
