name: .NET Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  # Adaptez la version .NET si nécessaire

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore

    - name: Run unit tests
      run: dotnet test --no-build --filter TestCategory=Unit

    - name: Run integration tests
      run: dotnet test --no-build --filter TestCategory=Integration
